# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param power.enableLutRouteBelPower 1
set_param power.enableCarry8RouteBelPower 1
set_param power.enableUnconnectedCarry8PinPower 1
set_param synth.incrementalSynthesisCache ./.Xil/Vivado-533-terminator/incrSyn
set_param power.BramSDPPropagationFix 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xczu3eg-sbva484-1-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.cache/wt [current_project]
set_property parent.project_path /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:ultra96:part0:1.0 [current_project]
set_property ip_repo_paths /home/t-1000/workspace/xilinx/hls/cv_hw [current_project]
set_property ip_output_repo /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
add_files /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/design_1_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_10/bd_afc3_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_16/bd_afc3_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_20/bd_afc3_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_21/bd_afc3_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_22/bd_afc3_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_23/bd_afc3_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_24/bd_afc3_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_25/bd_afc3_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_17/bd_afc3_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_18/bd_afc3_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_19/bd_afc3_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_11/bd_afc3_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_12/bd_afc3_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_2/bd_afc3_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_3/bd_afc3_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_4/bd_afc3_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_5/bd_afc3_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_6/bd_afc3_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_1/bd_afc3_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_1/bd_afc3_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_ila_0_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_ila_0_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_ila_0_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_ila_0_0/design_1_ila_0_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_ila_1_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_ila_1_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_ila_1_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_ila_1_0/design_1_ila_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_1/design_1_axi_dma_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_1/design_1_axi_dma_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_1/design_1_axi_dma_0_1_clocks.xdc]
set_property used_in_synthesis false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_ila_4_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_ila_4_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_ila_4_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_ila_4_0/design_1_ila_4_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_cv_hw_0_0/constraints/cv_hw_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_ila_2_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_ila_2_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_ila_2_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_ila_2_0/design_1_ila_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_4_0/design_1_axi_gpio_4_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_4_0/design_1_axi_gpio_4_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_4_0/design_1_axi_gpio_4_0.xdc]
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_rst_ps8_0_100M_0/design_1_rst_ps8_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_rst_ps8_0_100M_0/design_1_rst_ps8_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_rst_ps8_0_100M_0/design_1_rst_ps8_0_100M_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/sources_1/bd/design_1/design_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/constrs_1/new/ultra96_opencv.xdc
set_property used_in_implementation false [get_files /home/t-1000/workspace/xilinx/ultra96_opencv/ultra96_opencv.srcs/constrs_1/new/ultra96_opencv.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top design_1_wrapper -part xczu3eg-sbva484-1-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_1_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
