// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================


`timescale 1 ns / 1 ps

`define TV_OUT_op_stream_TDATA "./impl_rtl.cv_hw.autotvout_op_stream_V_data_V.dat"
`define EGRESS_STATUS_op_stream_TDATA "./stream_egress_status_op_stream_V_data_V.dat"
`define TV_OUT_op_stream_TKEEP "./impl_rtl.cv_hw.autotvout_op_stream_V_keep_V.dat"
`define EGRESS_STATUS_op_stream_TKEEP "./stream_egress_status_op_stream_V_keep_V.dat"
`define TV_OUT_op_stream_TSTRB "./impl_rtl.cv_hw.autotvout_op_stream_V_strb_V.dat"
`define EGRESS_STATUS_op_stream_TSTRB "./stream_egress_status_op_stream_V_strb_V.dat"
`define TV_OUT_op_stream_TUSER "./impl_rtl.cv_hw.autotvout_op_stream_V_user_V.dat"
`define EGRESS_STATUS_op_stream_TUSER "./stream_egress_status_op_stream_V_user_V.dat"
`define TV_OUT_op_stream_TLAST "./impl_rtl.cv_hw.autotvout_op_stream_V_last_V.dat"
`define EGRESS_STATUS_op_stream_TLAST "./stream_egress_status_op_stream_V_last_V.dat"
`define TV_OUT_op_stream_TID "./impl_rtl.cv_hw.autotvout_op_stream_V_id_V.dat"
`define EGRESS_STATUS_op_stream_TID "./stream_egress_status_op_stream_V_id_V.dat"
`define TV_OUT_op_stream_TDEST "./impl_rtl.cv_hw.autotvout_op_stream_V_dest_V.dat"
`define EGRESS_STATUS_op_stream_TDEST "./stream_egress_status_op_stream_V_dest_V.dat"

`define AUTOTB_TRANSACTION_NUM 1

module AESL_axi_s_op_stream (
    input clk,
    input reset,
    input [32 - 1:0] TRAN_op_stream_TDATA,
    input [4 - 1:0] TRAN_op_stream_TKEEP,
    input [4 - 1:0] TRAN_op_stream_TSTRB,
    input TRAN_op_stream_TUSER,
    input TRAN_op_stream_TLAST,
    input TRAN_op_stream_TID,
    input TRAN_op_stream_TDEST,
    input TRAN_op_stream_TVALID,
    output TRAN_op_stream_TREADY,
    input ready,
    input done,
    output [31:0] transaction);

    wire TRAN_op_stream_TVALID_temp;
    wire op_stream_TDATA_full;
    wire op_stream_TDATA_empty;
    reg op_stream_TDATA_write_en;
    reg [32 - 1:0] op_stream_TDATA_write_data;
    reg op_stream_TDATA_read_en;
    wire [32 - 1:0] op_stream_TDATA_read_data;
    
    fifo #(307200, 32) fifo_op_stream_TDATA (
        .reset(1'b0),
        .write_clock(clk),
        .write_en(op_stream_TDATA_write_en),
        .write_data(op_stream_TDATA_write_data),
        .read_clock(clk),
        .read_en(op_stream_TDATA_read_en),
        .read_data(op_stream_TDATA_read_data),
        .full(op_stream_TDATA_full),
        .empty(op_stream_TDATA_empty));
    
    always @ (*) begin
        op_stream_TDATA_write_en <= TRAN_op_stream_TVALID;
        op_stream_TDATA_write_data <= TRAN_op_stream_TDATA;
        op_stream_TDATA_read_en <= 0;
    end
    wire op_stream_TKEEP_full;
    wire op_stream_TKEEP_empty;
    reg op_stream_TKEEP_write_en;
    reg [4 - 1:0] op_stream_TKEEP_write_data;
    reg op_stream_TKEEP_read_en;
    wire [4 - 1:0] op_stream_TKEEP_read_data;
    
    fifo #(307200, 4) fifo_op_stream_TKEEP (
        .reset(1'b0),
        .write_clock(clk),
        .write_en(op_stream_TKEEP_write_en),
        .write_data(op_stream_TKEEP_write_data),
        .read_clock(clk),
        .read_en(op_stream_TKEEP_read_en),
        .read_data(op_stream_TKEEP_read_data),
        .full(op_stream_TKEEP_full),
        .empty(op_stream_TKEEP_empty));
    
    always @ (*) begin
        op_stream_TKEEP_write_en <= TRAN_op_stream_TVALID;
        op_stream_TKEEP_write_data <= TRAN_op_stream_TKEEP;
        op_stream_TKEEP_read_en <= 0;
    end
    wire op_stream_TSTRB_full;
    wire op_stream_TSTRB_empty;
    reg op_stream_TSTRB_write_en;
    reg [4 - 1:0] op_stream_TSTRB_write_data;
    reg op_stream_TSTRB_read_en;
    wire [4 - 1:0] op_stream_TSTRB_read_data;
    
    fifo #(307200, 4) fifo_op_stream_TSTRB (
        .reset(1'b0),
        .write_clock(clk),
        .write_en(op_stream_TSTRB_write_en),
        .write_data(op_stream_TSTRB_write_data),
        .read_clock(clk),
        .read_en(op_stream_TSTRB_read_en),
        .read_data(op_stream_TSTRB_read_data),
        .full(op_stream_TSTRB_full),
        .empty(op_stream_TSTRB_empty));
    
    always @ (*) begin
        op_stream_TSTRB_write_en <= TRAN_op_stream_TVALID;
        op_stream_TSTRB_write_data <= TRAN_op_stream_TSTRB;
        op_stream_TSTRB_read_en <= 0;
    end
    wire op_stream_TUSER_full;
    wire op_stream_TUSER_empty;
    reg op_stream_TUSER_write_en;
    reg [1 - 1:0] op_stream_TUSER_write_data;
    reg op_stream_TUSER_read_en;
    wire [1 - 1:0] op_stream_TUSER_read_data;
    
    fifo #(307200, 1) fifo_op_stream_TUSER (
        .reset(1'b0),
        .write_clock(clk),
        .write_en(op_stream_TUSER_write_en),
        .write_data(op_stream_TUSER_write_data),
        .read_clock(clk),
        .read_en(op_stream_TUSER_read_en),
        .read_data(op_stream_TUSER_read_data),
        .full(op_stream_TUSER_full),
        .empty(op_stream_TUSER_empty));
    
    always @ (*) begin
        op_stream_TUSER_write_en <= TRAN_op_stream_TVALID;
        op_stream_TUSER_write_data <= TRAN_op_stream_TUSER;
        op_stream_TUSER_read_en <= 0;
    end
    wire op_stream_TLAST_full;
    wire op_stream_TLAST_empty;
    reg op_stream_TLAST_write_en;
    reg [1 - 1:0] op_stream_TLAST_write_data;
    reg op_stream_TLAST_read_en;
    wire [1 - 1:0] op_stream_TLAST_read_data;
    
    fifo #(307200, 1) fifo_op_stream_TLAST (
        .reset(1'b0),
        .write_clock(clk),
        .write_en(op_stream_TLAST_write_en),
        .write_data(op_stream_TLAST_write_data),
        .read_clock(clk),
        .read_en(op_stream_TLAST_read_en),
        .read_data(op_stream_TLAST_read_data),
        .full(op_stream_TLAST_full),
        .empty(op_stream_TLAST_empty));
    
    always @ (*) begin
        op_stream_TLAST_write_en <= TRAN_op_stream_TVALID;
        op_stream_TLAST_write_data <= TRAN_op_stream_TLAST;
        op_stream_TLAST_read_en <= 0;
    end
    wire op_stream_TID_full;
    wire op_stream_TID_empty;
    reg op_stream_TID_write_en;
    reg [1 - 1:0] op_stream_TID_write_data;
    reg op_stream_TID_read_en;
    wire [1 - 1:0] op_stream_TID_read_data;
    
    fifo #(307200, 1) fifo_op_stream_TID (
        .reset(1'b0),
        .write_clock(clk),
        .write_en(op_stream_TID_write_en),
        .write_data(op_stream_TID_write_data),
        .read_clock(clk),
        .read_en(op_stream_TID_read_en),
        .read_data(op_stream_TID_read_data),
        .full(op_stream_TID_full),
        .empty(op_stream_TID_empty));
    
    always @ (*) begin
        op_stream_TID_write_en <= TRAN_op_stream_TVALID;
        op_stream_TID_write_data <= TRAN_op_stream_TID;
        op_stream_TID_read_en <= 0;
    end
    wire op_stream_TDEST_full;
    wire op_stream_TDEST_empty;
    reg op_stream_TDEST_write_en;
    reg [1 - 1:0] op_stream_TDEST_write_data;
    reg op_stream_TDEST_read_en;
    wire [1 - 1:0] op_stream_TDEST_read_data;
    
    fifo #(307200, 1) fifo_op_stream_TDEST (
        .reset(1'b0),
        .write_clock(clk),
        .write_en(op_stream_TDEST_write_en),
        .write_data(op_stream_TDEST_write_data),
        .read_clock(clk),
        .read_en(op_stream_TDEST_read_en),
        .read_data(op_stream_TDEST_read_data),
        .full(op_stream_TDEST_full),
        .empty(op_stream_TDEST_empty));
    
    always @ (*) begin
        op_stream_TDEST_write_en <= TRAN_op_stream_TVALID;
        op_stream_TDEST_write_data <= TRAN_op_stream_TDEST;
        op_stream_TDEST_read_en <= 0;
    end
    assign TRAN_op_stream_TVALID = TRAN_op_stream_TVALID_temp;

    
    assign TRAN_op_stream_TREADY = ~(op_stream_TDATA_full || op_stream_TKEEP_full || op_stream_TSTRB_full || op_stream_TUSER_full || op_stream_TLAST_full || op_stream_TID_full || op_stream_TDEST_full);
    
    function is_blank_char(input [7:0] in_char);
        if (in_char == " " || in_char == "\011" || in_char == "\012" || in_char == "\015") begin
            is_blank_char = 1;
        end else begin
            is_blank_char = 0;
        end
    endfunction
    
    function [199:0] read_token(input integer fp);
        integer ret;
        begin
            read_token = "";
                    ret = 0;
                    ret = $fscanf(fp,"%s",read_token);
        end
    endfunction
    
    function [199:0] rm_0x(input [199:0] token);
        reg [199:0] token_tmp;
        integer i;
        begin
            token_tmp = "";
            for (i = 0; token[15:0] != "0x"; token = token >> 8) begin
                token_tmp = (token[7:0] << (8 * i)) | token_tmp;
                i = i + 1;
            end
            rm_0x = token_tmp;
        end
    endfunction
    
    reg done_1;
    
    always @ (posedge clk or reset) begin
        if (~reset) begin
            done_1 <= 0;
        end else begin
            done_1 <= done;
        end
    end
    
    reg [31:0] transaction_save_op_stream_TDATA;
    
    assign transaction = transaction_save_op_stream_TDATA;
    
    initial begin : AXI_stream_receiver_op_stream_TDATA
        integer fp;
        reg [32 - 1:0] data;
        reg [8 * 5:1] str;
        
        transaction_save_op_stream_TDATA = 0;
        fifo_op_stream_TDATA.clear();
        wait (reset === 1);
        forever begin
            @ (negedge clk);
            if (done_1 == 1) begin
                fp = $fopen(`TV_OUT_op_stream_TDATA, "a");
                if (fp == 0) begin // Failed to open file
                    $display("ERROR: Failed to open file \"%s\"!", `TV_OUT_op_stream_TDATA);
                    $finish;
                end
                $fdisplay(fp, "[[transaction]] %d", transaction_save_op_stream_TDATA);
                while (~fifo_op_stream_TDATA.empty) begin
                    fifo_op_stream_TDATA.pop(data);
                    $fdisplay(fp, "0x%x", data);
                end
                $fdisplay(fp, "[[/transaction]]");
                transaction_save_op_stream_TDATA = transaction_save_op_stream_TDATA + 1;
                fifo_op_stream_TDATA.clear();
                $fclose(fp);
            end
        end
    end
    
    reg [31:0] transaction_save_op_stream_TKEEP;
    
    initial begin : AXI_stream_receiver_op_stream_TKEEP
        integer fp;
        reg [4 - 1:0] data;
        reg [8 * 5:1] str;
        
        transaction_save_op_stream_TKEEP = 0;
        fifo_op_stream_TKEEP.clear();
        wait (reset === 1);
        forever begin
            @ (negedge clk);
            if (done_1 == 1) begin
                fp = $fopen(`TV_OUT_op_stream_TKEEP, "a");
                if (fp == 0) begin // Failed to open file
                    $display("ERROR: Failed to open file \"%s\"!", `TV_OUT_op_stream_TKEEP);
                    $finish;
                end
                $fdisplay(fp, "[[transaction]] %d", transaction_save_op_stream_TKEEP);
                while (~fifo_op_stream_TKEEP.empty) begin
                    fifo_op_stream_TKEEP.pop(data);
                    $fdisplay(fp, "0x%x", data);
                end
                $fdisplay(fp, "[[/transaction]]");
                transaction_save_op_stream_TKEEP = transaction_save_op_stream_TKEEP + 1;
                fifo_op_stream_TKEEP.clear();
                $fclose(fp);
            end
        end
    end
    
    reg [31:0] transaction_save_op_stream_TSTRB;
    
    initial begin : AXI_stream_receiver_op_stream_TSTRB
        integer fp;
        reg [4 - 1:0] data;
        reg [8 * 5:1] str;
        
        transaction_save_op_stream_TSTRB = 0;
        fifo_op_stream_TSTRB.clear();
        wait (reset === 1);
        forever begin
            @ (negedge clk);
            if (done_1 == 1) begin
                fp = $fopen(`TV_OUT_op_stream_TSTRB, "a");
                if (fp == 0) begin // Failed to open file
                    $display("ERROR: Failed to open file \"%s\"!", `TV_OUT_op_stream_TSTRB);
                    $finish;
                end
                $fdisplay(fp, "[[transaction]] %d", transaction_save_op_stream_TSTRB);
                while (~fifo_op_stream_TSTRB.empty) begin
                    fifo_op_stream_TSTRB.pop(data);
                    $fdisplay(fp, "0x%x", data);
                end
                $fdisplay(fp, "[[/transaction]]");
                transaction_save_op_stream_TSTRB = transaction_save_op_stream_TSTRB + 1;
                fifo_op_stream_TSTRB.clear();
                $fclose(fp);
            end
        end
    end
    
    reg [31:0] transaction_save_op_stream_TUSER;
    
    initial begin : AXI_stream_receiver_op_stream_TUSER
        integer fp;
        reg [1 - 1:0] data;
        reg [8 * 5:1] str;
        
        transaction_save_op_stream_TUSER = 0;
        fifo_op_stream_TUSER.clear();
        wait (reset === 1);
        forever begin
            @ (negedge clk);
            if (done_1 == 1) begin
                fp = $fopen(`TV_OUT_op_stream_TUSER, "a");
                if (fp == 0) begin // Failed to open file
                    $display("ERROR: Failed to open file \"%s\"!", `TV_OUT_op_stream_TUSER);
                    $finish;
                end
                $fdisplay(fp, "[[transaction]] %d", transaction_save_op_stream_TUSER);
                while (~fifo_op_stream_TUSER.empty) begin
                    fifo_op_stream_TUSER.pop(data);
                    $fdisplay(fp, "0x%x", data);
                end
                $fdisplay(fp, "[[/transaction]]");
                transaction_save_op_stream_TUSER = transaction_save_op_stream_TUSER + 1;
                fifo_op_stream_TUSER.clear();
                $fclose(fp);
            end
        end
    end
    
    reg [31:0] transaction_save_op_stream_TLAST;
    
    initial begin : AXI_stream_receiver_op_stream_TLAST
        integer fp;
        reg [1 - 1:0] data;
        reg [8 * 5:1] str;
        
        transaction_save_op_stream_TLAST = 0;
        fifo_op_stream_TLAST.clear();
        wait (reset === 1);
        forever begin
            @ (negedge clk);
            if (done_1 == 1) begin
                fp = $fopen(`TV_OUT_op_stream_TLAST, "a");
                if (fp == 0) begin // Failed to open file
                    $display("ERROR: Failed to open file \"%s\"!", `TV_OUT_op_stream_TLAST);
                    $finish;
                end
                $fdisplay(fp, "[[transaction]] %d", transaction_save_op_stream_TLAST);
                while (~fifo_op_stream_TLAST.empty) begin
                    fifo_op_stream_TLAST.pop(data);
                    $fdisplay(fp, "0x%x", data);
                end
                $fdisplay(fp, "[[/transaction]]");
                transaction_save_op_stream_TLAST = transaction_save_op_stream_TLAST + 1;
                fifo_op_stream_TLAST.clear();
                $fclose(fp);
            end
        end
    end
    
    reg [31:0] transaction_save_op_stream_TID;
    
    initial begin : AXI_stream_receiver_op_stream_TID
        integer fp;
        reg [1 - 1:0] data;
        reg [8 * 5:1] str;
        
        transaction_save_op_stream_TID = 0;
        fifo_op_stream_TID.clear();
        wait (reset === 1);
        forever begin
            @ (negedge clk);
            if (done_1 == 1) begin
                fp = $fopen(`TV_OUT_op_stream_TID, "a");
                if (fp == 0) begin // Failed to open file
                    $display("ERROR: Failed to open file \"%s\"!", `TV_OUT_op_stream_TID);
                    $finish;
                end
                $fdisplay(fp, "[[transaction]] %d", transaction_save_op_stream_TID);
                while (~fifo_op_stream_TID.empty) begin
                    fifo_op_stream_TID.pop(data);
                    $fdisplay(fp, "0x%x", data);
                end
                $fdisplay(fp, "[[/transaction]]");
                transaction_save_op_stream_TID = transaction_save_op_stream_TID + 1;
                fifo_op_stream_TID.clear();
                $fclose(fp);
            end
        end
    end
    
    reg [31:0] transaction_save_op_stream_TDEST;
    
    initial begin : AXI_stream_receiver_op_stream_TDEST
        integer fp;
        reg [1 - 1:0] data;
        reg [8 * 5:1] str;
        
        transaction_save_op_stream_TDEST = 0;
        fifo_op_stream_TDEST.clear();
        wait (reset === 1);
        forever begin
            @ (negedge clk);
            if (done_1 == 1) begin
                fp = $fopen(`TV_OUT_op_stream_TDEST, "a");
                if (fp == 0) begin // Failed to open file
                    $display("ERROR: Failed to open file \"%s\"!", `TV_OUT_op_stream_TDEST);
                    $finish;
                end
                $fdisplay(fp, "[[transaction]] %d", transaction_save_op_stream_TDEST);
                while (~fifo_op_stream_TDEST.empty) begin
                    fifo_op_stream_TDEST.pop(data);
                    $fdisplay(fp, "0x%x", data);
                end
                $fdisplay(fp, "[[/transaction]]");
                transaction_save_op_stream_TDEST = transaction_save_op_stream_TDEST + 1;
                fifo_op_stream_TDEST.clear();
                $fclose(fp);
            end
        end
    end

endmodule
