// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xcv_hw.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XCv_hw_CfgInitialize(XCv_hw *InstancePtr, XCv_hw_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Ctrl_bus_BaseAddress = ConfigPtr->Ctrl_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XCv_hw_Start(XCv_hw *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCv_hw_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XCV_HW_CTRL_BUS_ADDR_AP_CTRL) & 0x80;
    XCv_hw_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XCV_HW_CTRL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XCv_hw_IsDone(XCv_hw *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCv_hw_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XCV_HW_CTRL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XCv_hw_IsIdle(XCv_hw *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCv_hw_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XCV_HW_CTRL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XCv_hw_IsReady(XCv_hw *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCv_hw_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XCV_HW_CTRL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XCv_hw_EnableAutoRestart(XCv_hw *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCv_hw_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XCV_HW_CTRL_BUS_ADDR_AP_CTRL, 0x80);
}

void XCv_hw_DisableAutoRestart(XCv_hw *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCv_hw_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XCV_HW_CTRL_BUS_ADDR_AP_CTRL, 0);
}

void XCv_hw_Set_rows(XCv_hw *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCv_hw_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XCV_HW_CTRL_BUS_ADDR_ROWS_DATA, Data);
}

u32 XCv_hw_Get_rows(XCv_hw *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCv_hw_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XCV_HW_CTRL_BUS_ADDR_ROWS_DATA);
    return Data;
}

void XCv_hw_Set_cols(XCv_hw *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCv_hw_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XCV_HW_CTRL_BUS_ADDR_COLS_DATA, Data);
}

u32 XCv_hw_Get_cols(XCv_hw *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCv_hw_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XCV_HW_CTRL_BUS_ADDR_COLS_DATA);
    return Data;
}

void XCv_hw_Set_flag(XCv_hw *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCv_hw_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XCV_HW_CTRL_BUS_ADDR_FLAG_DATA, Data);
}

u32 XCv_hw_Get_flag(XCv_hw *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCv_hw_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XCV_HW_CTRL_BUS_ADDR_FLAG_DATA);
    return Data;
}

void XCv_hw_InterruptGlobalEnable(XCv_hw *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCv_hw_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XCV_HW_CTRL_BUS_ADDR_GIE, 1);
}

void XCv_hw_InterruptGlobalDisable(XCv_hw *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCv_hw_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XCV_HW_CTRL_BUS_ADDR_GIE, 0);
}

void XCv_hw_InterruptEnable(XCv_hw *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XCv_hw_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XCV_HW_CTRL_BUS_ADDR_IER);
    XCv_hw_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XCV_HW_CTRL_BUS_ADDR_IER, Register | Mask);
}

void XCv_hw_InterruptDisable(XCv_hw *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XCv_hw_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XCV_HW_CTRL_BUS_ADDR_IER);
    XCv_hw_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XCV_HW_CTRL_BUS_ADDR_IER, Register & (~Mask));
}

void XCv_hw_InterruptClear(XCv_hw *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCv_hw_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XCV_HW_CTRL_BUS_ADDR_ISR, Mask);
}

u32 XCv_hw_InterruptGetEnabled(XCv_hw *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCv_hw_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XCV_HW_CTRL_BUS_ADDR_IER);
}

u32 XCv_hw_InterruptGetStatus(XCv_hw *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCv_hw_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XCV_HW_CTRL_BUS_ADDR_ISR);
}

