// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XCV_HW_H
#define XCV_HW_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xcv_hw_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Ctrl_bus_BaseAddress;
} XCv_hw_Config;
#endif

typedef struct {
    u32 Ctrl_bus_BaseAddress;
    u32 IsReady;
} XCv_hw;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XCv_hw_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XCv_hw_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XCv_hw_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XCv_hw_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XCv_hw_Initialize(XCv_hw *InstancePtr, u16 DeviceId);
XCv_hw_Config* XCv_hw_LookupConfig(u16 DeviceId);
int XCv_hw_CfgInitialize(XCv_hw *InstancePtr, XCv_hw_Config *ConfigPtr);
#else
int XCv_hw_Initialize(XCv_hw *InstancePtr, const char* InstanceName);
int XCv_hw_Release(XCv_hw *InstancePtr);
#endif

void XCv_hw_Start(XCv_hw *InstancePtr);
u32 XCv_hw_IsDone(XCv_hw *InstancePtr);
u32 XCv_hw_IsIdle(XCv_hw *InstancePtr);
u32 XCv_hw_IsReady(XCv_hw *InstancePtr);
void XCv_hw_EnableAutoRestart(XCv_hw *InstancePtr);
void XCv_hw_DisableAutoRestart(XCv_hw *InstancePtr);

void XCv_hw_Set_rows(XCv_hw *InstancePtr, u32 Data);
u32 XCv_hw_Get_rows(XCv_hw *InstancePtr);
void XCv_hw_Set_cols(XCv_hw *InstancePtr, u32 Data);
u32 XCv_hw_Get_cols(XCv_hw *InstancePtr);
void XCv_hw_Set_flag(XCv_hw *InstancePtr, u32 Data);
u32 XCv_hw_Get_flag(XCv_hw *InstancePtr);

void XCv_hw_InterruptGlobalEnable(XCv_hw *InstancePtr);
void XCv_hw_InterruptGlobalDisable(XCv_hw *InstancePtr);
void XCv_hw_InterruptEnable(XCv_hw *InstancePtr, u32 Mask);
void XCv_hw_InterruptDisable(XCv_hw *InstancePtr, u32 Mask);
void XCv_hw_InterruptClear(XCv_hw *InstancePtr, u32 Mask);
u32 XCv_hw_InterruptGetEnabled(XCv_hw *InstancePtr);
u32 XCv_hw_InterruptGetStatus(XCv_hw *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
