// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern void AESL_WRAP_cv_hw (
hls::stream<struct ap_axiu<32, 1, 1, 1 > > (&in_stream),
hls::stream<struct ap_axiu<32, 1, 1, 1 > > (&op_stream),
unsigned short rows,
unsigned short cols,
unsigned char flag);
