// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xcv_hw.h"

extern XCv_hw_Config XCv_hw_ConfigTable[];

XCv_hw_Config *XCv_hw_LookupConfig(u16 DeviceId) {
	XCv_hw_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XCV_HW_NUM_INSTANCES; Index++) {
		if (XCv_hw_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XCv_hw_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XCv_hw_Initialize(XCv_hw *InstancePtr, u16 DeviceId) {
	XCv_hw_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XCv_hw_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XCv_hw_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

